# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/steps/fmt.sh
        uses: ./ci/images/debian8
        with:
          args: ./ci/steps/fmt.sh

  lint:
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/steps/lint.sh
        uses: ./ci/images/debian8
        with:
          args: ./ci/steps/lint.sh
  release:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/steps/release.sh
        uses: ./ci/images/debian8
        with:
          args: ./ci/steps/release.sh
      - name: Upload npm package artifact
        uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: ./release-npm-package

  npm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/steps/publish-npm.sh
        uses: ./ci/images/debian8
        with:
          args: ./ci/steps/publish-npm.sh
